<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>1a29bc3d-fdef-482c-948f-49d23e60d2ee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.1" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\NetCoreBBS\NetCoreBBS.csproj" />
  </ItemGroup>

</Project>
